services:
  # A Docker web service
  - type: web
    name: server:1.0
    env: docker
 # optional
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: master # optional (defaults to master)
    rootDir: server 
    healthCheckPath: /